-- CreateEnum
CREATE TYPE "CardSource" AS ENUM ('WIKIPEDIA', 'ANILIST');

-- AlterTable
ALTER TABLE "Card" ADD COLUMN "source" "CardSource" NOT NULL DEFAULT 'WIKIPEDIA';

-- AlterTable
ALTER TABLE "User" ADD COLUMN "animePacks" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "animePacksRefilledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
